# fastlane/Fastfile

default_platform(:android)

platform :android do
  desc "Deploy to Play Store internal track"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '**/release/*.aab',
      json_key_data: ENV['GOOGLE_PLAY_KEY'],
      package_name: ENV['PACKAGE_NAME']
    )
  end
end
