name: Android CI & Auto Release


on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant gradlew permission
        run: chmod +x ./gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: '18'

#      - name: npm install
#        run: npm install

      - name: Install SDK Components
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Gradle 캐시 설정
        uses: gradle/gradle-build-action@v2

      - name: 유닛 테스트 실행
        run: ./gradlew testDebug

      - name: Debug APK 빌드
        run: ./gradlew :app:assembleDebug

      - name: Release Build
        run: ./gradlew assembleRelease

#      - name: APK zip 만들기
#        run: |
#          mkdir -p output
#          cp android/app/build/outputs/apk/debug/app-debug.apk output/
#          cd output && zip ../debug-apk.zip *
      - name: Create ZIP from APK
        run: |
          mkdir -p release_output
          cp android/app/build/outputs/apk/debug/app-debug.apk release_output/
          cd release_output && zip ../app-release.zip *

      - name: 리스트 확인
        run: ls -al app-release.zip

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

#      - name: Create Tag (Auto)
#        id: tagger
#        run: |
#          git config --global user.name "CI Bot"
#          git config --global user.email "ci@example.com"
#          export TAG_NAME=auto-$(date +'%Y%m%d-%H%M%S')
#          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
#          git tag $TAG_NAME
#          git push origin $TAG_NAME

      - name: Create Tag
        id: tagger
        run: |
          echo "TAG_NAME=auto-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: app-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}