name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK Components
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Gradlew 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 캐시 설정
        uses: gradle/gradle-build-action@v2

      - name: Debug APK 빌드
        run: ./gradlew assembleDebug

      - name: 유닛 테스트 실행
        run: ./gradlew testDebug

      - name: APK 업로드
        uses: actions/upload-artifact@3f51c3d0e346f3a4e8b02e1fe3e378cfc8ddc3ff
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Release Build
        run: ./gradlew assembleRelease