name: Android CI & Auto Release


on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant gradlew permission
        run: chmod +x ./gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SDK Components
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Gradle 캐시 설정
        uses: gradle/gradle-build-action@v2

      - name: 유닛 테스트 실행
        run: ./gradlew testDebug

      - name: Debug APK 빌드
        run: ./gradlew :app:assembleDebug

      - name: Release Build
        run: ./gradlew assembleRelease

      - name: Create ZIP from APK
        run: |
          mkdir -p release_output
          cp android/app/build/outputs/apk/debug/app-debug.apk release_output/
          cd release_output && zip ../app-release.zip *

      - name: 리스트 확인
        run: ls -al app-release.zip

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      #태그 생성
      - name: Create Tag
        id: tagger
        run: |
          echo "TAG_NAME=auto-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      #릴리즈 자동화 + 자동 릴리즈를 prerelease로 설정
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          prerelease: true
          files: app-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #최근 3개의 릴리즈만 남기고 태그포함 자동삭제
      - name: Delete Old Auto Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}